[package]
name = "type_sheaf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebra = "0.2.0"
num = "0.4.0"
ring = "0.16.20"
hex = "0.4.3"
